/**
 * Shiki transformer that replaces inline `style` attributes with class names so the
 * Content Security Policy can keep `style-src 'self'` (no 'unsafe-inline').
 *
 * Colours become `sh-<hex>` classes; font styles become `sh-italic`, `sh-bold`, `sh-underline`.
 * The matching stylesheet is generated by `scripts/generate-shiki-css.mjs` into
 * `src/styles/shiki.css` from the theme's palette.
 */

/**
 * @param {string} style
 * @returns {string[]}
 */
export function styleToClasses(style) {
  const classes = [];
  for (const declaration of style.split(';')) {
    const [rawProperty, ...rest] = declaration.split(':');
    if (!rawProperty || rest.length === 0) continue;
    const property = rawProperty.trim().toLowerCase();
    const value = rest.join(':').trim().toLowerCase();
    if (property === 'color' && value.startsWith('#')) {
      classes.push(`sh-${value.slice(1)}`);
    } else if (property === 'font-style' && value === 'italic') {
      classes.push('sh-italic');
    } else if (property === 'font-weight' && (value === 'bold' || Number(value) >= 600)) {
      classes.push('sh-bold');
    } else if (property === 'text-decoration' && value.includes('underline')) {
      classes.push('sh-underline');
    }
  }
  return classes;
}

/**
 * @param {{ properties?: Record<string, unknown> }} node
 */
function moveStyleToClass(node) {
  if (!node.properties) return;
  const style = node.properties.style;
  delete node.properties.style;
  if (typeof style !== 'string') return;
  const extra = styleToClasses(style);
  if (extra.length === 0) return;
  const existing = node.properties.class;
  const current = Array.isArray(existing)
    ? existing.map(String)
    : typeof existing === 'string'
      ? existing.split(/\s+/).filter(Boolean)
      : [];
  node.properties.class = [...current, ...extra].join(' ');
}

/** @returns {import('shiki').ShikiTransformer} */
export function shikiClassTransformer() {
  return {
    name: 'portfolio:inline-style-to-class',
    pre(node) {
      moveStyleToClass(node);
      node.properties.tabindex = 0;
    },
    code(node) {
      moveStyleToClass(node);
    },
    line(node) {
      moveStyleToClass(node);
    },
    span(node) {
      moveStyleToClass(node);
    },
  };
}
